C:\cygwin\home\ian\zz32\ghc-7.6.3\inplace\bin\haddock.exe --odir=libraries/process/dist-install/doc/html/process --no-tmp-comp-dir --dump-interface=libraries/process/dist-install/doc/html/process/process.haddock --html --hoogle --title=process-1.1.0.2: Process libraries --prologue=libraries/process/dist-install/haddock-prologue.txt --read-interface=../Win32-2.3.0.0,../Win32-2.3.0.0/src/%{MODULE/./-}.html#%{NAME},libraries/Win32/dist-install/doc/html/Win32/Win32.haddock --read-interface=../base-4.6.0.1,../base-4.6.0.1/src/%{MODULE/./-}.html#%{NAME},libraries/base/dist-install/doc/html/base/base.haddock --read-interface=../deepseq-1.3.0.1,../deepseq-1.3.0.1/src/%{MODULE/./-}.html#%{NAME},libraries/deepseq/dist-install/doc/html/deepseq/deepseq.haddock --read-interface=../directory-1.2.0.1,../directory-1.2.0.1/src/%{MODULE/./-}.html#%{NAME},libraries/directory/dist-install/doc/html/directory/directory.haddock --read-interface=../filepath-1.3.0.1,../filepath-1.3.0.1/src/%{MODULE/./-}.html#%{NAME},libraries/filepath/dist-install/doc/html/filepath/filepath.haddock --optghc=-H32m --optghc=-O --optghc=-package-name --optghc=process-1.1.0.2 --optghc=-hide-all-packages --optghc=-i --optghc=-ilibraries/process/. --optghc=-ilibraries/process/dist-install/build --optghc=-ilibraries/process/dist-install/build/autogen --optghc=-Ilibraries/process/dist-install/build --optghc=-Ilibraries/process/dist-install/build/autogen --optghc=-Ilibraries/process/include --optghc=-optP-Dbase4 --optghc=-optP-include --optghc=-optPlibraries/process/dist-install/build/autogen/cabal_macros.h --optghc=-package --optghc=Win32-2.3.0.0 --optghc=-package --optghc=base-4.6.0.1 --optghc=-package --optghc=deepseq-1.3.0.1 --optghc=-package --optghc=directory-1.2.0.1 --optghc=-package --optghc=filepath-1.3.0.1 --optghc=-split-objs --optghc=-XHaskell98 --optghc=-XCPP --optghc=-O2 --optghc=-no-user-package-db --optghc=-rtsopts --optghc=-odir --optghc=libraries/process/dist-install/build --optghc=-hidir --optghc=libraries/process/dist-install/build --optghc=-stubdir --optghc=libraries/process/dist-install/build --optghc=-hisuf --optghc=hi --optghc=-osuf --optghc=o --optghc=-hcsuf --optghc=hc --source-module=src/%{MODULE/./-}.html --source-entity=src/%{MODULE/./-}.html#%{NAME} libraries/process/./System/Process/Internals.hs libraries/process/./System/Process.hs libraries/process/./System/Cmd.hs +RTS -tlibraries/process/dist-install/doc/html/process/process.haddock.t --machine-readable 
 [("bytes allocated", "160756712")
 ,("num_GCs", "27")
 ,("average_bytes_used", "9905848")
 ,("max_bytes_used", "26505572")
 ,("num_byte_usage_samples", "5")
 ,("peak_megabytes_allocated", "46")
 ,("init_cpu_seconds", "0.00")
 ,("init_wall_seconds", "0.00")
 ,("mutator_cpu_seconds", "0.19")
 ,("mutator_wall_seconds", "0.70")
 ,("GC_cpu_seconds", "0.17")
 ,("GC_wall_seconds", "0.21")
 ]
